[workspace]
members = ["nanvm-lib", "nanvm"]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
authors = ["Sergey Shandar", "Denys Shandar"]
license = "GPL-3.0-or-later"
repository = "https://github.com/functionalscript/nanvm"

[workspace.dependencies]
wasm-bindgen-test = "0.3.39"
