[package]
name = "nanvm"
version = "0.0.0"
edition = "2021"
authors = ["Sergey Shandar"]
license = "GPL-3.0-or-later"
description = "NaNVM"
repository = "https://github.com/functionalscript/nanvm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
wasm-bindgen-test = "0.3.38"
