name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cargo fmt --check

  test:

    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-13']
        type: ['', '--release']

    runs-on: ${{ matrix.os }}

    steps:
    - run: rustup update
    - uses: actions/checkout@v4
    - run: sysctl -n machdep.cpu.brand_string
      if: matrix.os == 'macos-13'
    - run: cargo build ${{ matrix.type }}
    - run: cargo test --verbose ${{ matrix.type }}

  test-wasm:
    strategy:
      matrix:
        type: ['', '--release']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@wasm-pack
      - run: wasm-pack test --node ${{ matrix.type }} ./nanvm-lib

  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm test
    - run: npm run json
