name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustc --version
    - run: cargo clippy --all-targets --all-features -- -D warnings

  test:

    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-14']
        type: ['', '--release']
        target: ['']
        include:
          - os: windows-latest
            target: '--target i686-pc-windows-msvc'

    runs-on: ${{ matrix.os }}

    steps:
    - run: rustup update
    - uses: actions/checkout@v4
    - run: sysctl -n machdep.cpu.brand_string
      if: matrix.os == 'macos-14'
    - run: cargo build ${{ matrix.type }} ${{ matrix.target }}
    - run: cargo test --verbose ${{ matrix.type }} ${{ matrix.target }}

  test-wasm:
    strategy:
      matrix:
        type: ['', '--release']
    runs-on: ubuntu-latest
    steps:
      - run: rustup update
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@wasm-pack
      - run: wasm-pack test --node ${{ matrix.type }} ./nanvm-lib

  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm test
    - run: npm run json
